# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: 🦈 Hunt

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  hunt:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup dotenv
        run: echo ${{ secrets.DOTENV }} | base64 --decode > ./.env

      - name: Setup Go environment
        uses: actions/setup-go@v5.2.0

      - name: Build
        run: go build -tags with_utls,with_grpc -o megalodon ./main.go

      - name: Run
        run: ./megalodon

      - name: commit blacklist
        if: ${{ always() }}
        run: |
          git config --global user.name "Github Actions"
          git config --global user.email "actions@github.com"
          git add blacklist.txt
          git commit -m "update blacklist"
          git push origin main
