# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: 🦈 Hunt

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  hunt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup dotenv
        run: echo ${{ secrets.DOTENV }} | base64 --decode > ./.env

      - name: Setup Go environment
        uses: actions/setup-go@v5.2.0

      - name: Override DNS
        run: |
          echo "nameserver 1.1.1.1" | sudo tee /etc/resolv.conf > /dev/null

      - name: Build
        run: go build -tags with_utls,with_grpc -o megalodon ./main.go

      - name: Run
        run: ./megalodon

      - name: Save results alternatively
        if: failure()
        run: |
          curl --header "Content-Type: application/json" -d "{\"query\": \"$(cat query.txt | tr -d \\n\\t)\"}" https://api.foolvpn.me/db/${{ secrets.API_TOKEN }}/exec
